name = "friday"
pages_build_output_dir = "public"
compatibility_date = "2024-05-01"

# Konfigurasi spesifik untuk direktori Functions di dalam proyek Pages
[functions]
# Secara eksplisit memberitahu build system untuk menyediakan
# binding AI untuk semua worker di dalam direktori ini.
bindings.AI = { type = "ai" }
