# Nama proyek Anda di Cloudflare.
# Ini akan menjadi bagian dari URL *.pages.dev Anda.
name = "friday"

# Memberi tahu Cloudflare bahwa file frontend (HTML, CSS, JS)
# berada di dalam folder 'public'.
pages_build_output_dir = "public"

# PENTING: Baris ini memberitahu Cloudflare untuk menggunakan versi build
# terbaru yang kompatibel dengan fitur-fitur modern seperti Workers AI.
compatibility_date = "2024-05-01"

# CARA YANG BENAR UNTUK MENGAKTIFKAN AI DI PAGES FUNCTIONS
# Sintaks ini secara khusus memberitahu Pages untuk menyediakan
# layanan Workers AI dan menempatkannya di bawah `env.AI`
# di dalam kode functions/api.js Anda.
# Menggunakan [ai] (satu kurung siku) mendefinisikannya sebagai objek,
# sesuai dengan pesan error.
[ai]
binding = "AI"
