name = "friday"
pages_build_output_dir = "public"
compatibility_date = "2024-05-01"

# Konfigurasi spesifik untuk direktori Functions
[functions]
# Secara eksplisit menunjuk ke direktori tempat Functions Anda berada
directory = "./functions" 
# Binding ini akan memberitahu runtime DAN build system untuk menangani @cloudflare/ai
bindings.AI = { type = "ai" }
